#!/bin/sh

# create namespace oauth2tenant

kubectl create namespace oauth2tenant \
  --dry-run=client -o yaml | kubectl apply -f -

# create repo secret oauth2tenant.greymatter-admin-sync

kubectl create secret generic \
  --type="greymatter.io/repo" \
  --from-literal=url=git@github.com:mikejlong60/oauth2tenant.git \
  --from-literal=branch=main \
  --from-literal=auth_type=ssh \
  --from-file=ssh_private_key=$HOME/.ssh/id_ed25519 \
  --from-file=known_hosts=$HOME/.ssh/known_hosts \
  -n oauth2tenant greymatter-admin-sync \
  --dry-run=client -o yaml | kubectl apply -f -

kubectl -n oauth2tenant create secret generic greymatter-edge-ingress \
  --from-file=tls.crt=edge.crt \
  --from-file=tls.key=edge.key \
  --from-file=ca.crt=edge.crt \
  --dry-run=client -o yaml | kubectl apply -f -


  kubectl create secret generic \
  --from-file=ca.crt=edge.crt \
  --from-file=tls.crt=edge.crt \
  --from-file=tls.key=edge.key \
  -n oauth2tenant greymatter-edge-ingress \
  --dry-run=client -o yaml | kubectl apply -f -

  kubectl apply -f nginx.yaml

  kubectl create namespace keycloak

  kubectl create secret generic keycloak-tls \
    --from-file=ca.crt=edge.crt \
    --from-file=tls.crt=edge.crt \
    --from-file=tls.key=edge.key \
    -n keycloak

  kubectl create secret generic keycloak-cert \
    --from-file=ca.crt=keycloak.crt \
    --from-file=tls.crt=keycloak.crt \
    --from-file=tls.key=keycloak.key \
    -n oauth2tenant

    kubectl apply -f keycloak.yaml
