// Code generated from envoy/extensions/watchdog/profile_action/v3/profile_action.proto. DO NOT EDIT.
package v3

import (
	"strings"
)

// Configuration for the profile watchdog action.
#ProfileActionConfig: {
	"@type": "type.googleapis.com/envoy.extensions.watchdog.profile_action.v3.ProfileActionConfig"

	// How long the profile should last. If not set defaults to 5 seconds.
	profile_duration?: string

	// File path to the directory to output profiles.
	profile_path!: string & strings.MinRunes(1)

	// Limits the max number of profiles that can be generated by this action
	// over its lifetime to avoid filling the disk.
	// If not set (i.e. it's 0), a default of 10 will be used.
	max_profiles?: uint64
}
