// Code generated from envoy/service/status/v3/csds.proto. DO NOT EDIT.
package v3

import (
	v3_1 "envoyproxy.io/envoy-cue/spec/type/matcher/v3"
	v3_2 "envoyproxy.io/envoy-cue/spec/config/core/v3"
	v3_3 "envoyproxy.io/envoy-cue/spec/admin/v3"
)

// Request for client status of clients identified by a list of NodeMatchers.
#ClientStatusRequest: {
	"@type": "type.googleapis.com/envoy.service.status.v3.ClientStatusRequest"

	// Management server can use these match criteria to identify clients.
	// The match follows OR semantics.
	node_matchers?: [...v3_1.#NodeMatcher]

	// The node making the csds request.
	node?: v3_2.#Node

	// If true, the server will not include the resource contents in the response
	// (i.e., the generic_xds_configs.xds_config field will not be populated).
	// [#not-implemented-hide:]
	exclude_resource_contents?: bool
}

// Detailed config (per xDS) with status.
// [#next-free-field: 8]
#PerXdsConfig: {
	"@type": "type.googleapis.com/envoy.service.status.v3.PerXdsConfig"

	// Config status generated by management servers. Will not be present if the
	// CSDS server is an xDS client.
	status?: #ConfigStatus

	// Client config status is populated by xDS clients. Will not be present if
	// the CSDS server is an xDS server. No matter what the client config status
	// is, xDS clients should always dump the most recent accepted xDS config.
	//
	// .. attention::
	//   This field is deprecated. Use :ref:`ClientResourceStatus
	//   <envoy_v3_api_enum_admin.v3.ClientResourceStatus>` for per-resource
	//   config status instead.
	client_status?: #ClientConfigStatus

	// oneof per_xds_config: at most one may be set
	*{} |
	{listener_config!: v3_3.#ListenersConfigDump} |
	{cluster_config!: v3_3.#ClustersConfigDump} |
	{route_config!: v3_3.#RoutesConfigDump} |
	{scoped_route_config!: v3_3.#ScopedRoutesConfigDump} |
	{endpoint_config!: v3_3.#EndpointsConfigDump}
}

// All xds configs for a particular client.
#ClientConfig: {
	"@type": "type.googleapis.com/envoy.service.status.v3.ClientConfig"

	// Node for a particular client.
	node?: v3_2.#Node

	// This field is deprecated in favor of generic_xds_configs which is
	// much simpler and uniform in structure.
	xds_config?: [...#PerXdsConfig]

	// Represents generic xDS config and the exact config structure depends on
	// the type URL (like Cluster if it is CDS)
	generic_xds_configs?: [...#ClientConfig_GenericXdsConfig]

	// For xDS clients, the scope in which the data is used.
	// For example, gRPC indicates the data plane target or that the data is
	// associated with gRPC server(s).
	client_scope?: string
}

// GenericXdsConfig is used to specify the config status and the dump
// of any xDS resource identified by their type URL. It is the generalized
// version of the now deprecated ListenersConfigDump, ClustersConfigDump etc
// [#next-free-field: 10]
#ClientConfig_GenericXdsConfig: {
	"@type": "type.googleapis.com/envoy.service.status.v3.ClientConfig.GenericXdsConfig"

	// Type_url represents the fully qualified name of xDS resource type
	// like envoy.v3.Cluster, envoy.v3.ClusterLoadAssignment etc.
	type_url?: string

	// Name of the xDS resource
	name?: string

	// This is the :ref:`version_info <envoy_v3_api_field_service.discovery.v3.DiscoveryResponse.version_info>`
	// in the last processed xDS discovery response. If there are only
	// static bootstrap listeners, this field will be ""
	version_info?: string

	// The xDS resource config. Actual content depends on the type
	xds_config?: {...}

	// Timestamp when the xDS resource was last updated
	last_updated?: string

	// Per xDS resource config status. It is generated by management servers.
	// It will not be present if the CSDS server is an xDS client.
	config_status?: #ConfigStatus

	// Per xDS resource status from the view of a xDS client
	client_status?: v3_3.#ClientResourceStatus

	// Set if the last update failed, cleared after the next successful
	// update. The *error_state* field contains the rejected version of
	// this particular resource along with the reason and timestamp. For
	// successfully updated or acknowledged resource, this field should
	// be empty.
	// [#not-implemented-hide:]
	error_state?: v3_3.#UpdateFailureState

	// Is static resource is true if it is specified in the config supplied
	// through the file at the startup.
	is_static_resource?: bool
}

#ClientStatusResponse: {
	"@type": "type.googleapis.com/envoy.service.status.v3.ClientStatusResponse"

	// Client configs for the clients specified in the ClientStatusRequest.
	config?: [...#ClientConfig]
}

// Status of a config from a management server view.
#ConfigStatus:
	// Status info is not available/unknown.
	"UNKNOWN" |

	// Management server has sent the config to client and received ACK.
	"SYNCED" |

	// Config is not sent.
	"NOT_SENT" |

	// Management server has sent the config to client but hasn’t received
	// ACK/NACK.
	"STALE" |

	// Management server has sent the config to client but received NACK. The
	// attached config dump will be the latest config (the rejected one), since
	// it is the persisted version in the management server.
	"ERROR"

// Config status from a client-side view.
#ClientConfigStatus:
	// Config status is not available/unknown.
	"CLIENT_UNKNOWN" |

	// Client requested the config but hasn't received any config from management
	// server yet.
	"CLIENT_REQUESTED" |

	// Client received the config and replied with ACK.
	"CLIENT_ACKED" |

	// Client received the config and replied with NACK. Notably, the attached
	// config dump is not the NACKed version, but the most recent accepted one. If
	// no config is accepted yet, the attached config dump will be empty.
	"CLIENT_NACKED" |

	// Client received an error from the control plane. The attached config
	// dump is the most recent accepted one. If no config is accepted yet,
	// the attached config dump will be empty.
	"CLIENT_RECEIVED_ERROR"
